### ISSUE TITLE
Create "Monte-Carlo" calculation of infectiousness-expectation.

### ISSUE THREAD

**Issue by omri312** [CoronaHakab/CoronaHakabModel#161]
**Point of contact:** Mor Shemesh

For the normalization of the matrix, we need the infectiousness-per-day-expectation.
In the future, the way we calculate this expectation now will not hold when we make the algorithms of the medical states and transitions more complex.

**Solution:**
We should calculate this expectation using a small "Monte Carlo" simulation -
We will take 1000 random agents, "infect" them and let them go through all states of the infection until they recover/die, and finally take an average on all of their expectations.
This should be pretty fast computationally, and run on the start of the simulation (and in separatly from the simulation) as part of the normalization stage.

**Implementation notes:**
1. When running the calculation we should uniformly pick agents _from the relevant agents generation_.
2. This should be implemented as a separate module (class). This is important as in the future we'd like to also see outputs from this calculation as a stand-alone and not only as part of the simulation.

**Comment by bgmoshe** [comment]
@mor-m-shemesh Just to be clear:
* You want to start with randomly infected 1000 agents
* Run the simulation where they are the only ones participating (we do not care about how much they infect)
* Run untill all of them die or recover
Now for questions:
* Expectation of what to do you want to calculate
* What do you mean by "from the relevant agents generation."
* If we want the probability to be in a certain state, we can formulate it as a set of linear equations and solve them, no? Since there are not a lot of states it should be fast

**Comment by bgmoshe** [comment]
@omri312 This needs extra clarification since it was changed. As I understand this is not used for normalization anymore, therefore I must know what kind of analysis do you want:
Expected time to be in some state vs Expected time in some stated conditioned that you visited it? Conditioned time to be in a state and leave it (meaning that if a person gets back to some state he is counted twice)
Are tehre more things we want to analyze from the state machine?
